name: "gcp vpc_network_module"
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - 'terraform-modules/gcp/vpc_network/**'
  push:
    branches:
      - main
    paths:
      - 'terraform-modules/gcp/vpc_network/**'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  module-creation:
    uses: terraform-modules-dwy/terraform-module-workspace/.github/workflows/z01-tf-module-creation-base.yml@main
    with:
      module_path: 'terraform-modules/gcp/vpc_network/'
    secrets:
      APP_ID : ${{secrets.APP_ID}}
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}
