name: Terraform Auto Documentation
on:
    workflow_call:
        inputs:
            module_path :
                description: 'path to the terraform module'
                required: true
                type: string
            username:
                description: 'valid username to create and push documentation readme file'
                required: true
                type: string
            organization:
                description: 'github organization name'
                required: true
                type: string
        secrets:
            APP_ID:
                description: 'Github application ID'
                required: true
            APP_PRIVATE_KEY:
                description: 'Github application Private key'
                required: true

jobs:
    auto-documentation:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        
        steps:
            - name: Get Token
              id: get_actions_token
              uses: peter-murray/workflow-application-token-action@v2
              with:
                application_id: ${{secrets.APP_ID}}
                application_private_key: ${{secrets.APP_PRIVATE_KEY}}
                organization: ${{inputs.organization}}

            - name: Action Checkout
              uses: actions/checkout@v4
              with:
                token: ${{steps.get_actions_token.outputs.token}}

            - name: Create readme.md for module
              uses: terraform-docs/gh-actions@v1.0.0
              with:
                working-dir: ${{inputs.module_path}}
                output-file: README.md
                output-method: inject
                git-push: "false"
                git-push-user-name: ${{inputs.username}}

            - name: Enable File Permissions
              run: cd .git ; sudo chgrp -R docker . ; sudo chmod -R g_rwX . ; sudo find . -type d -exec chmod g+s '{}' + ; cd ..

            - name: Push the file
              run: |
                git config --global user.name "${{inputs.username}}[bot]"
                git config --global user.email "${{secrets.APP_ID}}${{inputs.username}}[bot]@users.noreply.github.com"
                git add .
                git commit -m "Added the readme.md file to the module ${{inputs.module_path}}"
                git push origin main
              continue-on-error: true